version: 2
jobs:
  build:

    working_directory: ~/my-pet-clinic

    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:

      - checkout

      - restore_cache:
          key: my-pet-clinic-{{ checksum "pom.xml" }}

      - run: mvn install -DskipTests

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: my-pet-clinic-{{ checksum "pom.xml" }}

      - run: mvn integration-test

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar
